### ISSUE TITLE
Attach Lambda function to VPC

### ISSUE THREAD

**Issue by chamilad** [dealmore/terraform-aws-next-js#110]
It doesn't look like the above can be done with this module, according to main.tf#55-75. Is it actually the case or am I just looking at the wrong code?

Also, if it is actually not possible, was there an explicit decision to not allow the option?

**Comment by ofhouse** [comment]
Hi, thanks for raising the question.

VPC support is on my radar, but didn't have enough time for exploring that feature so far.
It's one of the goals of this project to leverage the full potential of the regional Lambdas, since most projects in this area use Lambda@Edge which is limited in those capabilities.

But since we aim for an enterprise use of Next.js here VPC would be a great addition IMO 👍

**Comment by chamilad** [comment]
Awesome! I have this WIP PR that I'm testing on a project at the moment. I'll move it to be reviewable if all the scenarios I have in mind pass (as in functions get attached, correct routing, correct permissions). 

https://github.com/dealmore/terraform-aws-next-js/pull/111
