### ISSUE TITLE
Provider produced inconsistent final plan 0.8.0

### ISSUE THREAD

**Issue by JoviDeCroock** [dealmore/terraform-aws-next-js#113]
When upgrading to 0.8.0 for the Terraform module I started seeing:

```
When expanding the plan for
module.tf_next.module.statics_deploy.module.deploy_trigger.aws_lambda_function.this[0]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.last_modified: was known, but now unknown.
```

Is there something that needs to be changed? The config used for the Terraform setup is quite default:

```
  create_image_optimization = false

  providers = {
    aws.global_region = aws.global_region
  }
```

The unexpected change is on: `source_code_hash` for `module.tf_next.module.statics_deploy.module.deploy_trigger.aws_lambda_function.this[0]`

**Comment by JoviDeCroock** [comment]
This seems to be an issue on my side 😅

**Comment by ofhouse** [comment]
Yes and no, have seen this before on our upgrades as well. 😄 
This always seem to happen when we upgrade a Lambda component (proxy, deploy trigger, etc.), since it gets refetched while `terraform apply` is running which changes the signature of the downloaded file, which produces this inconsistency.

When running a second `terraform apply` after the message appears the issue should be resolved.
Don't see any chance to solve this on the module layer, so the idea here is to replace [NPM Download Terraform module](https://github.com/dealmore/terraform-npm-download) with an appropriate provider sometime soon.
