### ISSUE TITLE
Error creating S3 bucket: TooManyBuckets

### ISSUE THREAD

**Issue by andrewgadziksonos** [dealmore/terraform-aws-next-js#15]
Hello,

I'm receiving an error when using your module,

```
Error: Error creating S3 bucket: TooManyBuckets: You have attempted to create more buckets than allowed
	status code: 400, request id: 89C5F67086889131, host id: wPdV165nEmLi92mhhOCI9nHNt+jUk+zjIFTMbv/Se08jx9y/YJa9S1VRigzKN/0h81bgiCXr8M4=



Error: Error creating S3 bucket: TooManyBuckets: You have attempted to create more buckets than allowed
	status code: 400, request id: 4B5FF648E1B79D5F, host id: lbtIJiUVxVAspB1El4JxvFOz4IXHc4hmnxVUy4OCFmibrrjkjnlEoqIS0DQJmsggJD+9wUOw3DE=



Error: Error creating S3 bucket: TooManyBuckets: You have attempted to create more buckets than allowed
	status code: 400, request id: 1DC100A1565DABF8, host id: dH5aVMqbDQE9MnVMXpK9RzMjGTuJPF7CJXoduXUVrgKDQjq3O8RN5zotxCWISlhLdQSzYAgRx/A=
```

My TF file is the following,

```
provider "aws" {
  version = "~> 3.0"
  region = "us-east-1"
}

module "lambdas" {
  source  = "dealmore/next-js/aws"

  deployment_name = "test-app-sandbox"
  create_domain_name_records = false
}
```

I've followed the following steps,

1. terraform init
2. yarn tf-next
3. terraform plan
4. terraform apply 

Not sure if I'm doing something wrong and any help is appreciated!  Thank you in advance!

**Comment by ofhouse** [comment]
Hi,
your configuration seems fine.

I would say that the message comes from the underlying AWS SDK that you cannot create any more S3 buckets because that would exceed the limit of [100 per account](https://docs.aws.amazon.com/general/latest/gr/s3.html#limits_s3).

This module creates 3 new S3 buckets in your account so you should have a maximum of 97 buckets already in your account.
(You can always ask the AWS support for an increase to 1000 buckets per account).

Can you confirm that you have 97 or less buckets already in your account (So that creating 3 more buckets would not exceed the 100 limit)?

Anyway, we'll give the readme an update soon to list the number of each resource the module is creating.

**Comment by andrewgadziksonos** [comment]
Hey @ofhouse - thanks for the quick response! 

Yeah, wow our account is over 100 buckets - I've requested an increase.  Thanks for the help!
