### ISSUE TITLE
How to npm install v.0.9.1?

### ISSUE THREAD

**Issue by romansemko** [dealmore/terraform-aws-next-js#157]
It seems that the latest version on npm repo is 0.7.0. Installation from git is failing:

```
❯ npm i -D https://github.com/dealmore/terraform-aws-next-js/releases/tag/v0.9.1
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/dealmore/terraform-aws-next-js/releases/tag/v0.9.1.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

**Comment by ofhouse** [comment]
Hey,

this is intensional, since the terrafom module and the `tf-next` package have independent versioning.

So while latest version of the Terrafom module is `0.9.1` the latest version of the npm package `tf-next` is `0.7.0`

We release updates to the Terrafom module more often than updates to `tf-next` so the idea is that you don't have to update `tf-next` every time you update the module.

The module has a version checking built in, so if you try to use a version of the terrafom module with an incompatible version of `tf-next`  the deployment will fail with a message that you should update to the latest `tf-next` version.

Sorry for the confusion, hope this helps 😁

**Comment by romansemko** [comment]
It does thanks!
