### ISSUE TITLE
Proxy config not updated

### ISSUE THREAD

**Issue by romansemko** [dealmore/terraform-aws-next-js#158]
I have a project where I added new api routes. I see in S3 proxy config that the new route has been added correctly. However, when trying to access the route I get the standard static 404 page from the next.js project. It seems that the proxy is routing the request to static instead of API lambda.

I had this in the past and I thought that invalidating both proxy and main CF solved the issue. But somehow it does not do the trick any more...

**Comment by ofhouse** [comment]
Need some more info here, so that we can reproduce the routing behavior.

Can you post the file-structure where the missing API route is located in your project? (e.g. `pages/api/some-route/my-route.ts`)

**Comment by romansemko** [comment]
Sure. It's `/api/actions/[chainId]/info.js`

**Comment by romansemko** [comment]
Indeed, past behaviour was with similar structure like `/api/folder/[dynamic id folder]/xyz`

**Comment by ofhouse** [comment]
Created this text fixture for dynamic api routes but was not able to reproduce the issue with it (both e2e tests and deployment to AWS are doing fine here): #160

Any special config in the `next.config.js` (rewrites to api routes) that could lead to this issue?

**Comment by romansemko** [comment]
No. But I have noticed that after a few hours the route started working. IT is an actively used application. Can it be that the proxy reads the config when it's started and doesn't read it while the function is kept "hot" and is not killed until it's not used any more for a while?

**Comment by ofhouse** [comment]
Yes, the proxy fetches the config on the first run and keeps it while it's hot, since AWS has no mechanism in place to kill already running instances without redeploying the whole function (which takes a few minutes since this would require a CloudFront distribution update).

We always try to keep the CloudFront distribution updates to a minimum.

**Comment by romansemko** [comment]
I see. So is there a way to redeploy the whole function automatically when API endpoints are changed (especially when new ones are added) in order to force proxy restart?

**Comment by ofhouse** [comment]
Um, that's a difficult story.
Terraform uses a md5 hash on the source code of the Lambda to determine if a new version should be published (which would trigger a CloudFront deployment).
Since the Proxy is delivered as fixed package that cannot be changed during terraform apply this would not be an option.

You could try to handle this on the application side by using a versioned API schema (e.g. `/api/v1/actions...`).

The general plan to circumvent this issue is to use something like atomic deployments.
So that each deployment does not override the existing deployment, but instead creates a new one and the old remains available until the proxy is fully updated.

**Comment by romansemko** [comment]
Got it. Thanks for all your help and time. I now know better how it behaves under the hood, which makes my life and deployment decisions much easier. Awesome project! 🙌
