### ISSUE TITLE
Dynamic routes not working

### ISSUE THREAD

**Issue by andrewgadziksonos** [dealmore/terraform-aws-next-js#16]
Hello!

I'm seeing issues with dynamic pages and I just wanted to make sure that it's not something I'm doing incorrectly.  Here's my `tf-next` build output,

![image](https://user-images.githubusercontent.com/31038519/100470952-3c0ba580-30a7-11eb-97b8-fcf97335f066.png)

You can see that I have a mix of dynamic routes, catch-all routes and optional catch-all routes.

Going to https://d1hjov1nk12qxr.cloudfront.net/products/one results in a 404, but going to https://d1hjov1nk12qxr.cloudfront.net/products/[pid] results in rendered HTML.

Here's a zip of my test repo,

[nextjs-aws-demo.zip](https://github.com/dealmore/terraform-aws-next-js/files/5608957/nextjs-aws-demo.zip)

Thanks for the help in advance,

Andrew

**Comment by andrewgadziksonos** [comment]
I realized that I forgot to add a `next.config.js` file to the repo, after adding the following,

```
module.exports = {
  // Build the server for a serverless environment
  target: 'serverless',
};
```

and rebuilding, I'm still seeing the same errors

**Comment by ofhouse** [comment]
Thanks for creating & posting that example.
Will take a deeper look tomorrow. Could be possible that something broke with the latest Next.js 10 release, we haven't upgraded yet.

**Comment by andrewgadziksonos** [comment]
I’ll also try and downgrade to 9.5 later and see if that fixes it. Thanks!

**Comment by andrewgadziksonos** [comment]
Hmm - That didn't seem to help.  Using `next@9.5.5` still produces 404s - no errors in the logs.  Let me know if you need anything else from me.

**Comment by ofhouse** [comment]
Sorry for the delay. Checked it out and got the same result, so routing is definitely broken for this example.
Currently gearing up a better testing solution for real world examples which I expect to ship by tomorrow and then I can take a better look what happened in this case.

**Comment by andrewgadziksonos** [comment]
No worries, and sounds good.  I'm happy to help debug if needed

**Comment by ofhouse** [comment]
Short update regarding this issue:
I've tracked the issue down to this code:
https://github.com/dealmore/terraform-aws-next-js/blob/main/packages/proxy/src/proxy.ts#L92

This was a workaround introduced for slug routes (e.g. `/some-page/[...slug]`) that we mostly rely on for our own projects.
While it works for slug-routes it breaks dynamic routing (e.g. `/some-page/[id]`) at this point because it cuts the arguments from the URL and prevents the dynamic part from being passed to the lambda.

To prevent the issue in the future we set up an local e2e testing (proxy -> lambda) in #17 powered by AWS SAM and introduce further unit tests to cover that use cases.

Routing is a bit complicated here because it is mostly based on reverse engineering Vercel's proxy solution but with the testing we should have a solution ready soon.

**Comment by andrewgadziksonos** [comment]
Thanks @ofhouse for the update!  Looking forward to the fix.  Let me know how I can help

**Comment by ofhouse** [comment]
@andrewgadziksonos ok, end of the year was busier than I thought, so sorry again for the delay on this issue 🙈.

I finally implemented a working solution for the issue and the e2e tests results also confirm that it is working.
I track the current status in #17 and when CI is green we are ready for a new release 😬

Unfortunately there is still one test failing for a [fallback route](https://nextjs.org/docs/basic-features/data-fetching#fallback-pages).
Since fallback routes didn't work before either I think this is not necessarily linked to this issue and we may defer support for fallback routes in a feature request.
Will make decision on this tomorrow and then I will publish a new release.

**Comment by ofhouse** [comment]
Good news, we finally have a new `v0.2.0` release out that should fix the issue.

Please note that you also need to update the `@dealmore/terraform-next-build` in your `package.json` to `0.2.0`.
