### ISSUE TITLE
AWS CLI Windows - Deploying & Hosting NextJs SSR app Cannot find distribution folder

### ISSUE THREAD

**Issue by IbrahimSam96** [dealmore/terraform-aws-next-js#164]
Oh, forgot to mention there is a third option:

You can install the [AWS CLI](https://aws.amazon.com/cli/) and then set the `use_awscli_for_static_upload` attribute, which then uses the AWS CLI to perform the task that previously needed Bash and wGet.

```diff
...

module "tf_next" {
  source = "dealmore/next-js/aws"

+ use_awscli_for_static_upload = true

  providers = {
    aws.global_region = aws.global_region
  }
}

```

Not tested, but this should work on Windows.

_Originally posted by @ofhouse in https://github.com/dealmore/terraform-aws-next-js/issues/148#issuecomment-866173714_

**Comment by IbrahimSam96** [comment]
- I have added the `use_awscli_for_static_upload` attribute in the basic `main.tf` file 
- Downloaded Amplify-Cli `npm install -g @aws-amplify/cli` 
-  `amplify init`

? Enter a name for the project: `graphx`
? Enter a name for the environment: `dev`
? Choose your default editor: `Visual Studio Code (or your preferred editor) `
? Choose the type of app that youre building: `javascript`
? What javascript framework are you using: `react`
? Source Directory Path: `src`
? Distribution Directory Path: `build`
? Build Command: `npm run-script tf-next`
? Start Command: `npm run-script start
`? Do you want to use an `AWS profile? Y

`amplify publish 
`
//Executes both `tf-next `and then `build`

![amplifyCLIProb](https://user-images.githubusercontent.com/72482204/126592561-dccd6db1-84a5-4903-a6e6-15afdc0d5cb8.PNG)

```

**Comment by ofhouse** [comment]
Hi, the module is exclusive for [Terrafom](https://www.terraform.io/) so it's not compatible with other deployment solutions such as AWS Amplify.

Amplify has built-in Next.js support that doesn't require `tf-next`: https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js

Please note that AWS CLI and AWS Amplify are two different products.

**Comment by IbrahimSam96** [comment]
Hi, 

Thanks for your quick response. 

I have tried deploying a SSR Next.js app build using Amplify, however had received 503 [error](https://stackoverflow.com/questions/68447671/how-to-deploy-nextjs-ssr-app-on-amplify-with-lambdaedge-503-error). I'am still unsure how to fix :/

**Comment by ofhouse** [comment]
It looks like you are using the AWS Amplify service to deploy your application.
AWS Amplify is the all-in-one solution from AWS to deploy applications like Next.js on AWS.

The module here is built on top of Terraform which is developed by Hashicorp and uses a different approach to deploy Applications to different cloud providers like AWS.

You cannot mix these technologies together since they are using different data structures to manage the application stack.
If you have problems with AWS Amplify you should contact the AWS support or open an issue at their repository: https://github.com/aws-amplify/amplify-js
