### ISSUE TITLE
Support for Multi Zones

### ISSUE THREAD

**Issue by matheus-guimaraes** [dealmore/terraform-aws-next-js#167]
Hi,

Would this module support multi zones? For example, using the example app with zones, if we create the app with "npx create-next-app --example with-zones with-zones-app " would the build treat them as one app and update the lambda proxy, deploy their APIs and static content accordingly?

thanks :)

**Comment by ofhouse** [comment]
Hi, short answer is no, it does not support multi-zones.
Deployment is currently limited to a single Next.js app per CloudFront distribution.

**Comment by matheus-guimaraes** [comment]
thank you so much for your reply :)  Are there any plans to support multi zones? I don't see any mentions on the list of features that you intend to bring in future releases.

**Comment by ofhouse** [comment]
Multi-zones is unfortunately not that easy to develop because it needs more groundwork first.
On Vercel it works like this:
```
example.com/a* -> deployment-abc_1234567
example.com/b* -> deployment-def_3246312
example.com/c* -> deployment-ghi_2189122
```
so each route is assigned a different deployment, that works independent from the other.
The module is currently designed to hold only a single deployment at a time.

So before we could support multi-zones we have to develop a solution to support multiple deployments (Which is the same Feature as preview deployments on Vercel).

Ultimately it's only a question of time how many features can be implemented. I have no fixed roadmap for the module but the time I can spend on this project is limited since I don't make money from it 🙈

**Comment by matheus-guimaraes** [comment]
thanks so much for the detailed response, it's really helpful. and thank you so much for all your efforts, it's much appreciated by everyone :)
