### ISSUE TITLE
Triggering terraform resource updates when nextjs code changes

### ISSUE THREAD

**Issue by jamesla** [dealmore/terraform-aws-next-js#23]
I have the following file main.tf which sits in the root of my repo and deploys my next app great via terraform cloud.

```hcl
provider "aws" {
  region  = "us-east-1"
}

module "lambdas" {
  source  = "dealmore/next-js/aws"
  deployment_name          = "codecitizen"
  lambda_memory_size = 128
}
```

It deploys fine but I can't seem to figure out how to make it update the underlying terraform resources when my nextjs application code changes as the module doesn't seem to expose any triggers etc.

I did try hacking it by doing the following:

```hcl
resource "null_resource" "hack" {
  triggers = {
    policy_sha1 = "${sha1(file("src/index.js"))}"
  }
}

module "lambdas" {
  source  = "dealmore/next-js/aws"
  deployment_name          = "codecitizen"
  lambda_memory_size = 128

  depends_on = [null_resource.hack]
}
```

but since the module still has terraform 12 support then it doesn't support module depends_on

When the nextjs code changes how can I get the module to pick up on the change and then update the underlying terraform resources?

**Comment by ofhouse** [comment]
Hi James, thanks for reaching out.

The Terraform module does not perform a rebuild of the application on its own when running ‘terraform apply‘.

Building or rebuilding the application is done with the ‘tf-next build‘ command via npm or yarn. This creates (or overrides an existing) ‘.tf-next/‘ folder where the bundled application is stored.

When running ‘terraform apply‘ afterwards, the module checks for changes exclusively in this ‘.tf-next/‘ folder.

That means in order to update your application you have to run the commands in this order:

1. ‘tf-next build‘ command (to update the app bundle)
2. ‘terraform apply‘ to deploy the updated bundle to the resources


Coming from a Vercel or Serverless flow this may seem unintuitive because they perform the build and deploy step in one single step.
But we split the two steps by design because for our own setup we perform the build step and the Terraform commands on two separate machines (in CI/CD) to make use of different pre-configured Docker images that are optimized for each step.

This worked for months without extra configuration while using Terraform 0.12 (We upgraded our systems just last week), so you should not need any workarounds in order to make it work.

**Comment by ofhouse** [comment]
@jamesla does it solve your question?

**Comment by jamesla** [comment]
@ofhouse Yes it does I got this fixed up this weekend and deploying nicely. Thanks for such a detailed explanation 👍
