### ISSUE TITLE
`create` variable

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [dealmore/terraform-aws-next-js#78]
many terraform module support `create` or `create_xx` variables to controls whether resource should be created. I think, one of the reasons for doing this is, it's hard to use `count` or `for_each` in module block.

`terraform-aws-next-js` also has `create_domain_name_records`  and `create_image_optimization`. But no option to skip for other resources. 

Do you have any plans to add a `create` variable that controls the creation of the entire resource? Or can I create a PR?

**Comment by ofhouse** [comment]
Do you have a specific resource in mind?
My philosophy here is to support optional resources when they are not necessary or can be replaced with self-written constructs.

The next optional resource to add will be the main CloudFront distribution, which is targeted in #55.
IMHO I currently don't see other resources where this would make sense, but I am open for suggestions 🙂

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@ofhouse In many use cases, one Terraform code covers multiple environments. For example, in the code below, I would like to decide to create the next-tf module according to the environment.

```terraform
module "next-tf" {
  source = "dealmore/next-js/aws"
  create = terraform.workspace == "prod"
  // or
  // create = var.env == "prod"

  next_tf_dir     = var.next_tf_dir
  deployment_name = var.deployment_name
}
```

This pattern can be used in many modules, including the following two modules used by this module:
- https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2
- https://github.com/terraform-aws-modules/terraform-aws-lambda

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
> My philosophy here is to support optional resources when they are not necessary or can be replaced with self-written constructs.

This can also be achieved by just using `var.create && var.create_xxx`.

```
resouce "cloudfront_distribution" "this" {
  count = var.create && var.cloudfront_distribution ? 1 : 0
}
```

**Comment by ofhouse** [comment]
Ah, thanks for clarification.
I think the `create` variables there were originally added for versions of below Terraform `0.13` since it was not possible to use `count` or `for_each` on modules.

Terraform `0.13` (which is already the minimal required version for this module) and up support [`count` on modules](https://www.terraform.io/docs/language/meta-arguments/count.html) which I would prefer here since it is an official Terraform feature and no workaround like a `create` variable would be.

However, using count on this module currently does not work because we use an internal AWS provider to ensure that some resources are created in `us-east-1` region.
The plan is to drop this internal provider in the next version which should lift the limitation on using `count`.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
You're right. Using `count` in module block, prevents the use of provider inside the module, I think the `create` variable is still useful in many cases.

**Comment by ofhouse** [comment]
Would like to reevaluate this after #50 is implemented.
Introducing a create variable would require a lot of changes and it must also be ensured that the submodules support it.

For this reason I would appreciate it when this could be handled in userland with a simple count on the module itself.

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
